version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: joomla
       MYSQL_USER: joomla
       MYSQL_PASSWORD: password

   joomla:
     depends_on:
       - db
     image: joomla:latest
     ports:
       - "8000:80"
     restart: always
     volumes:
      - ./src/joomla:/var/www/html
     environment:
       JOOMLA_DB_HOST: db:3306
       JOOMLA_DB_USER: joomla
       JOOMLA_DB_PASSWORD: password
volumes:
    dbdata: